name: Robocop Analysis

on:
  push:
    branches:
      - "**"  # Triggers on all branches, including feature branches
      - "manual"
  workflow_dispatch:

jobs:
  robocop-check:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          pip install robotframework-robocop

      - name: Run Robocop
        run: |
          robocop . | tee output.txt  # Scan all .robot files, capture output

      - name: Upload Robocop Report (Optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: robocop-report
          path: output.txt
